services:
  qa_backend:
    build:
      context: ./PYTHON
      dockerfile: Dockerfile
    container_name: qa_backend
    restart: always
    env_file:
      - ./PYTHON/.env
    extra_hosts:
      - "mysql_standalone:host-gateway"
    networks:
      - web_network

networks:
  web_network:
    external: true