from datetime import date
from typing import Optional
from pydantic import BaseModel
import pymysql
from fastapi import APIRouter, Depends
from app.database import get_connection as get_db
from app.utils.auth_utils import get_current_user
from fastapi import HTTPException


class ConsumptionCreate(BaseModel):
    energy_type: str
    charge_code: str
    charge_name: str
    cost: float
    uom: str
    type: str
    charge_description: Optional[str]
    valid_upto: Optional[date]
    discount_charges: Optional[float]
    status: Optional[int] = None  # 1 = Active, 0 = Inactive
    is_submitted: Optional[int] = 0   # 0 = Save, 1 = Post


class FormulaRequest(BaseModel):
    charge_code: str
    cost: float
    uom: str
    type: str
    discount_charges: Optional[float] = 0

router = APIRouter(prefix="/consumption", tags=["Consumption"])

@router.post("/preview-formula")
def preview_formula(data: FormulaRequest):
    charge_code = data.charge_code
    cost = data.cost
    uom = str(data.uom).upper()
    charge_type = str(data.type).upper()
    discount = data.discount_charges or 0
    
    cost_expr = str(cost)
    if discount > 0:
        if discount == 50:
            cost_expr = f"({cost} / 2)"
        else:
            factor = discount / 100
            cost_expr = f"({cost} * {factor})"

    # Rule-based Formula Builder
    expr = cost_expr
    
    # 1. UOM Multipliers
    if "PAISA" in uom and "UNIT" in charge_type:
        # Special case for Paisa and Unit
        expr = f"({expr} * total units generated by windmill/solar in that month)"
    elif "UNIT" in uom or "MONTH" in uom:
        # per unit / per month per windmill = * total units generated by windmill
        expr = f"({expr} * total units generated by windmill/solar in that month)"
    
    if "MEGAWATT" in uom:
        # per megawatt = * capacity of the windmill
        expr = f"({expr} * capacity of the windmill)"
        
    # 2. Type Multipliers/Divisors
    if "YEAR" in charge_type:
        # year = /365 (shown as year in denominator)
        expr = f"({expr} / year)"
        
    # 2. Type Multipliers/Divisors
    if "YEAR" in charge_type:
        # year = /365 (shown as year in denominator)
        expr = f"[{expr} / year]"
        
    if ("MONTH" in charge_type or "YEAR" in charge_type) and "DAY" not in charge_type:
        # month = * no.of days in the month
        expr = f"{expr} * no.of days in a month"
    
    if "DAY" in charge_type:
        # day = cost itself (no days multiplication)
        pass

    return {"formula": expr.strip()}


@router.post("/add")
def add_consumption(data: ConsumptionCreate, user=Depends(get_current_user)):
    connection = get_db()
    cursor = connection.cursor()

    try:
        cursor.callproc("sp_create_consumption", [
            0,  # p_id (not used for insert)
            data.energy_type,
            data.charge_code,
            data.charge_name,
            data.cost,
            data.uom,
            data.type,
            data.charge_description,
            data.valid_upto,
            data.discount_charges,
            data.is_submitted,
            user["id"]
        ])

        connection.commit()

        return {
           
            "is_submitted": data.is_submitted
        }

    except Exception as e:
        connection.rollback()
        raise HTTPException(status_code=500, detail=str(e))

    finally:
        cursor.close()
        connection.close()


@router.get("/list")
def list_consumption(user=Depends(get_current_user)):

    db = get_db()
    cursor = db.cursor(pymysql.cursors.DictCursor)

    cursor.callproc("sp_get_consumption")

    return cursor.fetchall()


@router.get("/{id}")
def get_consumption(id: int, user=Depends(get_current_user)):

    db = get_db()
    cursor = db.cursor(pymysql.cursors.DictCursor)

    cursor.callproc("sp_get_consumption_by_id", (id,))

    return cursor.fetchone()


@router.put("/update/{id}")
def update_consumption(id: int, data: ConsumptionCreate, user=Depends(get_current_user)):
    connection = get_db()
    cursor = connection.cursor(pymysql.cursors.DictCursor)

    try:
        # Preserve existing row values for partial updates (in particular STATUS)
        cursor.callproc("sp_get_consumption_by_id", (id,))
        existing = cursor.fetchone()
        if not existing:
            raise HTTPException(status_code=404, detail="Consumption record not found")

        status = data.status if data.status is not None else existing.get("status", 1)
        is_submitted = data.is_submitted if data.is_submitted is not None else existing.get("is_submitted", 0)

        cursor.callproc("sp_update_consumption_record", (
            id,
            data.energy_type,
            data.charge_code,
            data.charge_name,
            data.cost,
            data.uom,
            data.type,
            data.charge_description,
            data.valid_upto,
            data.discount_charges,
            status,
            is_submitted,
            user["id"]
        ))

        connection.commit()

        return {
            "message": "Consumption updated successfully",
            "is_submitted": is_submitted,
            "status": status
        }

    except Exception as e:
        connection.rollback()
        raise HTTPException(status_code=500, detail=str(e))

    finally:
        cursor.close()
        connection.close()



@router.delete("/delete/{id}")
def delete_consumption(id: int, user=Depends(get_current_user)):

    db = get_db()
    cursor = db.cursor()

    try:
        cursor.callproc("sp_delete_consumption", (id,))
        db.commit()
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=400, detail=str(e))
    finally:
        cursor.close()
        db.close()

    return { "Consumption deleted successfully"}