server {
    listen 80;
    server_name resolvex.softcoretech.in;

    # Always keep this for future automatic renewals
    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html/resolvex/static;
    }

    # Redirect all other HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name resolvex.softcoretech.in;

    ssl_certificate /etc/letsencrypt/live/resolvex.softcoretech.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/resolvex.softcoretech.in/privkey.pem;

    # Explicitly handle the root for ResolveX
    location / {
        # Using a variable forces Nginx to ignore resolution until a request actually comes in
        resolver 127.0.0.11 valid=30s; 
        set $upstream_resolvex http://resolvex_backend:5000;
        
        # Change this line below:
        proxy_pass $upstream_resolvex; 

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location /static/ {
        alias /usr/share/nginx/html/resolvex/static/;
    }
}
