server {
    listen 80;
    server_name hrmsprototype.softcoretech.in;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name hrmsprototype.softcoretech.in;

    ssl_certificate /etc/letsencrypt/live/hrmsprototype.softcoretech.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hrmsprototype.softcoretech.in/privkey.pem;

    location / {
        root /usr/share/nginx/html/hrms_prototype/HRMS-PROTOTYPE-17Oct25;
        index index.html;
        try_files $uri $uri/ =404;
    }
}
